services:
  survey-service:
    build:
      context: ./survey_service
      dockerfile: Dockerfile
    image: opine/survey-service:1.0
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - surveyNetwork

  ai-rag-service:
    build:
      context: ./ai_rag_service
      dockerfile: Dockerfile
    image: opine/ai-rag-service:1.0
    ports:
      - "5008:5008"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - surveyNetwork

  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    image: opine/user-service:1.0
    ports:
      - "5001:5001"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - surveyNetwork

  voucher-service:
    build:
      context: ./voucher_service
      dockerfile: Dockerfile
    image: opine/vocher-service:1.0
    ports:
      - "5002:5002"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - surveyNetwork

  scheduler-service:
    build:
      context: ./scheduler_service
      dockerfile: Dockerfile
    image: opine/scheduler_service:1.0
    ports:
      - "5003:5003"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - surveyNetwork

  survey_publisher:
    build:
      context: ./survey_publisher/
      dockerfile: Dockerfile
    image: opine/survey-publisher:1.0
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PYTHONUNBUFFERED=1
    # restart: always
    container_name: survey-publisher
    ports:
      - "5004:5004"
    networks:
      - surveyNetwork

  authenticator:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    image: opine/authenticator:1.0
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PYTHONUNBUFFERED=1
    # restart: always
    ports:
      - "5005:5005"
    networks:
      - surveyNetwork
  recsys:
    build:
      context: ./recsys_service
      dockerfile: Dockerfile
    image: opine/recsys:1.0
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PYTHONUNBUFFERED=1
    # restart: always
    ports:
      - "5006:5006"
    networks:
      - surveyNetwork

  addable:
    build:
      context: ./addable_service
      dockerfile: Dockerfile
    image: opine/addable:1.0
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PYTHONUNBUFFERED=1
    # restart: always
    ports:
      - "5009:5009"
    networks:
      - surveyNetwork

  payment:
    build:
      context: ./payment_service
      dockerfile: Dockerfile
    image: opine/payment:1.0
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - PYTHONUNBUFFERED=1
    # restart: always
    ports:
      - "5010:5010"
    networks:
      - surveyNetwork

  responses:
    build:
      context: ./responses_service
      dockerfile: Dockerfile
    image: opine/responses:1.0
    ports:
      - "5101:5101"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY} # idk if I need? my script so far doesnt use
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - surveyNetwork
    container_name: responses-service
networks:
  surveyNetwork:
    driver: bridge
